---
- hosts: localhost
  gather_facts: False
  connection: local
  vars_files:
    - vcenter_vars.yml


  tasks:
  - name: Gather Facts of all VMs in variable machines.
    local_action:
      module: vmware_vm_facts
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
    register: facts

  - name: Verbose output of action
    debug:
      var: facts.virtual_machines

